<?php
$variable['error_email']='support@easywebmanager.lt';
$variable['send_error_email']=0;
$variable['pr_code']='cms';
$variable['pr_email']='info@easywebmanager.lt';
$variable['license']='20120727---VYTAUTAS---2712---3.8---8131';
$variable['key']='46613e7e787f2b5da6f48d71d6da5cb3';
$variable['project_start_date']='2012-07-27';
$variable['default_lng']='lt';
$variable['default_page']['lt']=3345;
$variable['default_page']['en']=3345;
$variable['default_page']['ru']=3345;
$variable['default_page']['de']=3345;
$variable['pr_url']='vytautas';
$variable['project_dir']='/easy/3.8/';
$variable['admin_dir']='admin/';
$variable['hostname']='localhost';
$variable['username']='root';
$variable['password']='root';
$variable['database']='easy_38';
$variable['ftp_hostname']='';
$variable['ftp_port']='21';
$variable['ftp_dirpath']='';
$variable['ftp_username']='';
$variable['ftp_password']='';
?>