<?php
$variable['error_email']='support@easywebmanager.lt';
$variable['send_error_email']=0;
$variable['pr_code']='cms';
$variable['pr_email']='info@easywebmanager.lt';
$variable['license']='20110721---VYTAUTAS---2712---3.7---7903';
$variable['key']='74833173e39830b085963a383913753c';
$variable['project_start_date']='2011-07-21';
$variable['default_lng']='lt';
$variable['default_page']['lt']=3345;
$variable['default_page']['en']=3345;
$variable['default_page']['ru']=3345;
$variable['default_page']['de']=3345;
$variable['pr_url']='vytautas';
$variable['project_dir']='/eshop/';
$variable['admin_dir']='admin/';
$variable['hostname']='localhost';
$variable['username']='root';
$variable['password']='root';
$variable['database']='eshop';
$variable['ftp_hostname']='';
$variable['ftp_port']='21';
$variable['ftp_dirpath']='';
$variable['ftp_username']='';
$variable['ftp_password']='';
?>